### ISSUE TITLE
TypeError: Cannot read property 'closed' of null

### ISSUE THREAD

**Issue by mjstelly** [proyecto26/MyApp#5]
App crashes when navigating from `Offline list` back to `Photo list`. Haven't tried on android.

Environment:
ios sim `iPhone 11 (iOS 13.4)`
"react": "16.11.0",
"react-native": "0.62.2",

Steps to reproduce:

1. Launch app and press the start button
2. Open drawer menu
3. Select `Offline list`
4. Reopen drawer menu
5. Select `Photo list`

![app crash](https://user-images.githubusercontent.com/313819/83412740-455dd300-a3e0-11ea-8474-afc3c692c2ce.png)

**Comment by mjstelly** [comment]
Oops. In my haste I forgot to complete the description.

**Comment by jdnichollsc** [comment]
Sorry for the mistake, the issue was fixed here https://github.com/proyecto26/MyApp/blob/feature/database-watermelondb/src/hooks/offline.ts#L15
